language: cpp
compiler: gcc
sudo: required
install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x 
  - sudo apt-get clean
  - sudo apt-get update
  - sudo apt-get purge cmake
  - sudo apt-get install -yq build-essential gcc-4.9 g++-4.9 gcc-4.9-multilib g++-4.9-multilib xorg-dev libglu1-mesa-dev x11-xserver-utils xorg openbox libxxf86vm-dev
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.6 40 --slave /usr/bin/g++ g++ /usr/bin/g++-4.6
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 80 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9
  - echo 2 | sudo update-alternatives --config gcc
  - wget http://www.cmake.org/files/v3.3/cmake-3.3.0-Linux-x86_64.tar.gz --no-check-certificate
  - tar -xzf cmake-3.3.0-Linux-x86_64.tar.gz
  - sudo cp -fR cmake-3.3.0-Linux-x86_64/* /usr
  - rm -rf cmake-3.3.0-Linux-x86_64
  - rm cmake-3.3.0-Linux-x86_64.tar.gz
  - g++ --version
  - cmake --version
  - mkdir build
  - cd build
  - cmake .. -G "Unix Makefiles"
script:
  - make
  - make test
